---
title: "Using the Equitable Transform"
author: "C. Elphinstone and R.D.Elphinstone"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

A method of scaling to maintain individuality
    The equitable transformation maintains systematic differences between instances when the underlying pattern is a separable function in two variables. This technique converts “equitably” between comparable instances in a dataset.
    Applied to a data set, it removes noise superimposed on an underlying signal enabling patterns to be extracted more easily from a 2D data set. Elphinstone, C. and Henry, G. (submitted to Ecosphere, 2019) show the multipurpose uses for the equitable transform. 


## Function to create transform information

Functions useful for analysing two dimensional data sets are included in this package. A two dimensional data set (d) is transformed via Td<-transformE(d) and a variety of matrices associated with the equitable transform is placed in Td. A signal data set can be made via d<-eg4(2,2) and noise can be added to make a noisy 2D data set (d_noise) in a variety of ways. 

## Functions to plot transform information

If Td and Td_noise are the results from running transformE then plotsummary(Td_noise,Td), plotsummary(Td) and plotsummary(Td_noise) summarize and plot information about the two transformations.



